//初始化的设置数据
var setting={
  "platformSetting": {
    "id": 116,
    "platformName": "花市集",
    "areaIdentify": "",
    "platformNo": "xianhua",
    "platformType": "",
    "rizhiNewsTypeId": 0,
    "yygShaidanNewsTypeId": 0,
    "defaultPlatform": 0,
    "orderNo": 0,
    "siteTitle": "花市集-鲜花批发",
    "topBgColor": "#FE7AAC",
    "topColor": "#ffffff",
    "bottomBgColor": "#FFFFFF",
    "indexPage": "custom_page_index.html",
    "secretCode": "",
    "singleModel": 1,
    "favicon": "http://image1.sansancloud.com/shuiguo/2017_12/07/09/29/37_907.jpg",
    "logo": "http://image1.sansancloud.com/shuiguo/2017_12/07/09/29/37_907.jpg",
    "description": "undefined",
    "keywords": "",
    "shopCount": 1,
    "expireDate": "2090-10-10 00:00:00",
    "createDate": "2017-12-11 10:36:58",
    "welcomImage": "",
    "bottomColor": "",
    "defaultColor": "#FE7AAC",
    "defaultBgColor": "#ffffff",
    "mainCss": ".rich_text{\r\npadding:12px;\r\n}\r\n#custom_page_index .menubar .menu  .imgTabIcon{\r\nwidth:24px !important;\r\nheight:24px !important;opacity:1 !important;\r\n} \r\n#custom_page_index  .menubar .menu.active  .imgTabIcon{\r\nwidth:0px !important;\r\nheight:0px !important;opacity:1 !important;\r\n} \r\n#custom_page_index  .menubar .menu:active  .imgTabIcon{\r\nwidth:0px !important;\r\nheight:0px !important;opacity:1 !important;\r\n} \r\n\r\n#custom_page_index .menubar .menu:active  .imgTabIconActive{\r\nwidth:24px !important;\r\nheight:24px !important;opacity:1 !important;\r\n} \r\n\r\n#custom_page_index .menubar .menu.active  .imgTabIconActive{\r\nwidth:24px !important;\r\nheight:24px !important;opacity:1 !important;\r\n}\r\n#custom_page_index .menubar .menu,#custom_page_index .menubar .menu{\r\n\tcolor:#909090;\r\n}\r\n#custom_page_index .menubar .menu:active,#custom_page_index .menubar .menu.active{\r\n\tcolor:#000;\r\n}\r\n#custom_page_index  .menubar .menu .menu-text{\r\nfont-size:11px;\r\n}\r\n#custom_page_index .menubar{\r\nbackground:#ffffff !important\r\n}\r\n#custom_page_ertongzhixing .menubar{\r\nbackground:#140b08 !important\r\n}\r\n.description img{\r\nwidth:100%;\r\n}\r\n\r\n.tab:active, .tab.active{\r\n    color: #000;\r\n    border-bottom: 2px solid #000;\r\n}",
    "mainScript": "",
    "shopNickName": "店铺",
    "defaultShop": 257,
    "defaultShopBean": {
      "id": 257,
      "shopName": "福州鲜花批发",
      "shopDescription": "",
      "shopLogo": "http://image1.sansancloud.com/xianhua/2018_01/23/15/24/47_195.jpg",
      "shopBanner": "http://image1.sansancloud.com/xianhua/2018_01/26/09/53/00_856.jpg",
      "belongAreaId": 0,
      "belongUserId": 0,
      "belongShangquanId": 0,
      "shopLevelId": 0,
      "hotShop": 0,
      "shopLevelValue": 0,
      "shopTip": "",
      "checkTime": "2017-12-11 10:39:26",
      "checkUserId": 0,
      "checkState": 1,
      "setEnable": 1,
      "platformNo": "xianhua",
      "telno": "",
      "range": 0,
      "ownerName": "",
      "favoriteCount": 0,
      "ownerQq": "12",
      "ownerEmail": "",
      "deleteFlag": 0,
      "turnover": 17531,
      "shopContent": "",
      "adverts": [],
      "productCount": 0,
      "platformShop": 0,
      "shopScore": 0,
      "scoreNum": 1,
      "averageScore": 0,
      "averageScoreHundred": 0,
      "shopOrder": 0,
      "shopIndexPage": "",
      "orderItems": [],
      "carItems": [],
      "shopFavorite": 0,
      "backOrderCount": 2,
      "maxOrderPerDay": 0,
      "todayOrderCount": 0,
      "serviceOrderCount": 5,
      "printerType": 1,
      "printerPartner": "",
      "printerMachineCode": "",
      "printerApiKey": "",
      "printerMachineKey": "",
      "wechatNo": "243",
      "kefuTelno": "",
      "shopLocation": "",
      "backAddress": "",
      "serviceStartTime": 0,
      "serviceEndTime": 24,
      "account": {
        "id": 43,
        "shopId": 257,
        "shopName": "福州鲜花批发",
        "platformNo": "xianhua",
        "account": 0,
        "mendianId": 0,
        "mendianBelongShop": 0
      }
    },
    // "miniAppid": "wx37b3f495891dd60c",
    "miniIndexPage": "",
    "wxMiniAuthAccessToken": "",
    "wxMiniAuthRefreshToken": "",
    "wxMiniAuthAccessTokenTime": 1521425001132,
    "wxMiniSecret": "",
    // "wxGzAppid": "wx415aa6f5cc06a3e4",
    "wxGzAuthAccessToken": "",
    "wxGzAuthRefreshToken": "",
    "wxGzShanghuhao": "",
    "wxGzShanghukey": "",
    "wxGzAuthAccessTokenTime": 1521427300054,
    "shortMsgUserName": "",
    "shortMsgPassword": "",
    "shortMsgSign": "",
    "caFile": "",
    "fxLevel": 1,
    "wxAutoLogin": 0,
    "authType": 0,
    "fxShenhe": 0,
    "zfHdfkEnable": 1,
    "zfZfbEnable": 1,
    "zfYezfEnable": 1,
    "zfWxzfEnable": 1,
    "zfWyzfEnable": 1,
    "zfOfflineEnable": 1,
    "zfHdfkOn": 0,
    "zfZfbOn": 0,
    "zfYezfOn": 0,
    "zfYezfHelpPage": "",
    "zfWxzfOn": 1,
    "zfWyzfOn": 0,
    "zfOfflineOn": 0,
    "zfOfflineHelpPage": "",
    "txHelpPage": "",
    "userNeedShenhe": 0,
    "platformLevel": 1,
    "userDefinedTemplate": 1,
    "appEnable": 1,
    "wapEnable": 1,
    "pcEnable": 0,
    "ruzhuPlatform": 0,
    "kucunPlatform": 0,
    "registSuccessTurnPage": "",
    "useLocate": 1,
    "unshowSalldown": 1,
    "jsapiTicket": "",
    "jingxiaoPriceScale": 1,
    "lingshouPriceScale": 1,
    "appName": "水果批发",
    "appDescription": "",
    "iosDownloadUrl": "",
    "androidDownloadUrl": "",
    "yingyongbaoUrl": "",
    "managerTelno": "",
    "zfbPartner": "",
    "zfbKey": "",
    "zfbSellerEmail": "",
    "zfbPrivateKey": "",
    "zfbPublicKey": "",
    "shopEarningBiliPercent": 0,
    "mendianDistributeProfit": 100,
    "mendianNickName": "门店",
    "orderDefaultMendianStrategy": 2,
    "defaultUserIcon": "http://image1.sansancloud.com/xianhua/2018_01/26/09/53/00_856.jpg",
    "jishuzhichi": "福州三三网络科技有限公司",
    "devKey": "",
    "wxConfig": "{\"appId\":\"wx415aa6f5cc06a3e4\",\"debug\":false,\"jsApiList\":[\"onMenuShareTimeline\",\"onMenuShareAppMessage\",\"onMenuShareQQ\",\"onMenuShareWeibo\",\"onMenuShareQZone\",\"startRecord\",\"stopRecord\",\"onVoiceRecordEnd\",\"playVoice\",\"pauseVoice\",\"stopVoice\",\"onVoicePlayEnd\",\"uploadVoice\",\"downloadVoice\"],\"nonceStr\":\"ce60ff163cab97029cc727e20e0fc3a7\",\"signature\":\"d3e64d50c3a0c99f27631ca8f486cbfd990235a6\",\"timestamp\":\"1521427433\"}",
    "wxDebugConfig": "{\"appId\":\"wx415aa6f5cc06a3e4\",\"debug\":true,\"jsApiList\":[\"onMenuShareTimeline\",\"onMenuShareAppMessage\",\"onMenuShareQQ\",\"onMenuShareWeibo\",\"onMenuShareQZone\",\"startRecord\",\"stopRecord\",\"onVoiceRecordEnd\",\"playVoice\",\"pauseVoice\",\"stopVoice\",\"onVoicePlayEnd\",\"uploadVoice\",\"downloadVoice\"],\"nonceStr\":\"1fe46a07a9ba5f05129cab882582d907\",\"signature\":\"674f99e7bded3249fab4259c05f6a12f5463166e\",\"timestamp\":\"1521427433\"}",
    "backOrderPeriod": 1,
    "maxBackOrderCount": 2,
    "alipayReturnUrl": "",
    "platformUiSettingBean": {
      "productDetailShow": 1,
      "productAttrShow": 1,
      "productShopShow": 1,
      "shopShowName": "店铺",
      "yongjinShowName": "佣金",
      "fenxiaoShowName": "分销商"
    },
    "platformTemplateSettingBean": {},
    "categories": [
      {
        "id": 1176,
        "name": "永生花",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/54/35_219.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      },
      {
        "id": 1175,
        "name": "绿植盆载",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/54/26_902.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      },
      {
        "id": 1174,
        "name": "礼盒花",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/53/45_614.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      },
      {
        "id": 1173,
        "name": "会议花",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/54/08_414.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      },
      {
        "id": 1172,
        "name": "花篮",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/53/30_445.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      },
      {
        "id": 1171,
        "name": "鲜花",
        "url": "",
        "parentId": 0,
        "children": [],
        "listTemplate": "",
        "detailTemplate": "",
        "iconImage": "http://image1.sansancloud.com/xianhua/2017_12/18/11/53/53_659.jpg",
        "description": "",
        "orderNo": 0,
        "platformNo": "xianhua",
        "showMenu": 0,
        "adverLink": ", ",
        "adverImg": ", ",
        "categoryCode": ""
      }
    ],
    "categoryList": [
      {
        "key": 1176,
        "value": "永生花"
      },
      {
        "key": 1175,
        "value": "绿植盆载"
      },
      {
        "key": 1174,
        "value": "礼盒花"
      },
      {
        "key": 1173,
        "value": "会议花"
      },
      {
        "key": 1172,
        "value": "花篮"
      },
      {
        "key": 1171,
        "value": "鲜花"
      }
    ],
    "newsTypes": [],
    "saleTypes": [
      {
        "id": 270,
        "typeName": "12",
        "parentId": 0,
        "typeIcon": "undefined",
        "leafType": 0,
        "platformNo": "xianhua",
        "children": []
      }
    ],
    "areas": [
      {
        "id": 46,
        "areaName": "华北",
        "parentId": 0,
        "areaCode": "undefined",
        "platformNo": "xianhua",
        "longitude": 0,
        "latitude": 0,
        "orderNo": 12,
        "leafArea": 1
      },
      {
        "id": 43,
        "areaName": "华南",
        "parentId": 0,
        "areaCode": "undefined",
        "platformNo": "xianhua",
        "longitude": 0,
        "latitude": 0,
        "orderNo": 1,
        "leafArea": 1
      },
      {
        "id": 44,
        "areaName": "华南",
        "parentId": 0,
        "areaCode": "undefined",
        "platformNo": "xianhua",
        "longitude": 0,
        "latitude": 0,
        "orderNo": 1,
        "leafArea": 1
      },
      {
        "id": 47,
        "areaName": "1211",
        "parentId": 0,
        "areaCode": "12",
        "platformNo": "xianhua",
        "longitude": 2,
        "latitude": 1,
        "orderNo": 1,
        "leafArea": 1
      },
      {
        "id": 42,
        "areaName": "hudong",
        "parentId": 0,
        "areaCode": "undefined",
        "platformNo": "xianhua",
        "longitude": 0,
        "latitude": 0,
        "orderNo": 0,
        "leafArea": 1
      }
    ],
    "properties": [],
    "expressStrategy": [
      {
        "id": 17,
        "name": "满50免邮",
        "expressType": 3,
        "defaultValue": 1,
        "defaultExpressAmount": 8,
        "addtionValue": 1,
        "additionAmount": 0,
        "platformNo": "xianhua",
        "orderAmountNoExpress": 50,
        "details": [],
        "expressTypeStr": "订单"
      }
    ],
    "platformWuliuComs": {
      "yd": "韵达"
    },
    "qiandaoJifen": 10,
    "shopSplite": 0,
    "pingjiaJifen": 10,
    "pingjiaZishu": 20,
    "jifenDikou": 0,
    "maxDikouJifen": 0,
    "minDikouJifen": 0,
    "registJifen": 10,
    "payJifen": 100,
    "userRegistDisable": 0,
    "wxAppAppid": "",
    "wxAppShanghuhao": "",
    "wxAppShanghukey": "",
    "wxAppCaFile": "",
    "tagTypes": "产品,店铺,新闻",
    "gainJifenPinfen": 0,
    "tagsMap": {
      "新闻": [],
      "产品": [],
      "店铺": []
    },
    "flashs": [],
    "wxAppSecret": "",
    "saleStrategy": {
      "0001": {
        "level_1": [
          {
            "id": 25,
            "belongStrategyNo": "0001",
            "belongStrategyName": "销售策略1",
            "userLevelValue": 1,
            "leastProductCount": 1,
            "strategyZhekou": 0.9,
            "platformNo": "xianhua"
          }
        ]
      }
    },
    "validateMailOpenAddress": "",
    "appIndexPage": "",
    "mustLogin": 0,
    "foreverQrcode": 0,
    "androidVersion": "",
    "iosVersion": "",
    "frontDomain": "www.sansancloud.com",
    "backDomain": "",
    "registMustTuijian": 0,
    "normalProduct": 1,
    "serviceProduct": 0,
    "viewProduct": 1,
    "presaleProduct": 0,
    "leaseProduct": 0,
    "defaultExpressStrategyNo": "",
    "continueQiandaoJifenList": [],
    "rechargeBili": 1,
    "wxPcAppid": "",
    "wxPcAppSecret": "d5b1914d92265cfe8b320a6e82663ce3",
    "giftIds": "",
    "wuliuCombind": 1,
    "prePlatformNo": "",
    "userLevels": [
      {
        "id": 25,
        "levelValue": 3,
        "levelName": "三级渠道1",
        "platformNo": "xianhua"
      },
      {
        "id": 24,
        "levelValue": 2,
        "levelName": "二级渠道",
        "platformNo": "xianhua"
      },
      {
        "id": 23,
        "levelValue": 1,
        "levelName": "一级渠道",
        "platformNo": "xianhua"
      }
    ]
  },
  "menus": null
}
export default setting;